version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /samkhya-py
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /samkhya-gpudb/scripts
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /samkhya-gpudb/scripts
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
